### PR TITLE
Changes to make the plugin compatible with dokku v3.15

### PR DESCRIPTION
**Pull request by pmvieira**
Dokku commands have changed, so:
- now to create an app we need to run apps:create
- we need to specify build step has the build method

This should make this registry:push compatible with Dokku v0.3.15

### CODE REVIEW

**Comment by yngndrw** [comment]
Buildstep should not be hardcoded, instead it should follow the logic that Dokku does:

``` bash
  if [[ -f Dockerfile ]] && [[ "$([[ -f .env ]] && grep -q BUILDPACK_URL .env; echo $?)" != "0" ]] && [[ ! -f ".buildpacks" ]]; then
    dokku receive "$APP" "dockerfile" "$TMP_WORK_DIR" | sed -u "s/^/"$'\e[1G'"/"
  else
    dokku receive "$APP" "buildstep" "$TMP_WORK_DIR" | sed -u "s/^/"$'\e[1G'"/"
  fi
```

**Comment by josegonzalez** [comment]
Dokku now has support for a tar-backed deploys:

``` shell
git archive --format tar.gz master | dokku tar:in python-sample
```

**Comment by josegonzalez** [comment]
Bump, any chance this can be merged?

**Comment by pmvieira** [comment]
sorry @josegonzalez and @yngndrw got married and been really busy.
Will try to get some time aside to make this nicer :)

**Comment by josegonzalez** [comment]
Great! If you can merge this in, I can make a separate PR to add 0.4.x support :)

**Comment by pmvieira** [comment]
Thanks for you suggestion @yngndrw 
I believe the code now reflects what you had in mind.

**Comment by yngndrw** [comment]
Looks good to me. :thumbsup:

**Comment by pmvieira** [comment]
Thanks @yngndrw.
Any changes this could be merged @kristofsajdak @kristofsajdak-agco ?

**Comment by kristofsajdak** [comment]
@pmvieira @yngndrw @josegonzalez 
Haven't looked into this for a while, but the changes definitely make sense

Also wanted to apologise for the delayed response, things have been very busy the last couple of months on my side as well and I kind of lost track of the messages here

**Pull request merged**
